"""Positive, negative and edge cases for POST /v1/disk/resources/upload."""

from __future__ import annotations

from hashlib import md5

import pytest
import requests

from yandex_disk_api import YandexDiskClient

from .conftest import (
    assert_error_response,
    unique_child,
    upload_test_file,
    wait_for_operation,
    wait_for_operation_result,
    wait_for_resource_state,
)

pytestmark = pytest.mark.integration

REMOTE_FILE_CONTENT = b"requests==2.32.5\n"
REMOTE_FILE_URL = (
    "https://raw.githubusercontent.com/Repkol/Yandex/"
    "372c9ed2ef77c0c728aac58d39c08ec3e65b244d/requirements.txt"
)


def assert_operation_link(
    response: requests.Response,
    *,
    expected_fields: set[str] | None = None,
) -> dict[str, object]:
    """Assert the documented asynchronous operation Link."""
    assert response.status_code == requests.codes.accepted
    assert response.headers["Content-Type"].startswith("application/json")
    payload = response.json()
    if expected_fields is not None:
        assert set(payload) == expected_fields
    assert payload["method"] == "GET"
    assert str(payload["href"]).startswith("https://")
    return payload


def assert_remote_file_uploaded(
    client: YandexDiskClient,
    path: str,
) -> dict[str, object]:
    """Assert exact metadata for the immutable external fixture."""
    wait_for_resource_state(client, path, exists=True, timeout=60.0)
    metadata = client.get_resource(path).json()
    assert metadata["path"] == path
    assert metadata["type"] == "file"
    assert metadata["size"] == len(REMOTE_FILE_CONTENT)
    assert metadata["md5"] == md5(REMOTE_FILE_CONTENT).hexdigest()
    return metadata


def numbered_collision_path(path: str) -> str:
    """Return the sibling name generated by Disk for the first collision."""
    parent, name = path.rsplit("/", maxsplit=1)
    if "." not in name:
        return f"{parent}/{name} (1)"
    stem, extension = name.rsplit(".", maxsplit=1)
    return f"{parent}/{stem} (1).{extension}"


def test_upload_from_url_happy_path_imports_exact_file(
    disk_client: YandexDiskClient,
    sandbox_path: str,
) -> None:
    """Happy Path: asynchronously import an immutable public file."""
    file_path = f"{unique_child(sandbox_path, 'remote-upload-happy')}.txt"

    response = disk_client.upload_resource_from_url(
        file_path,
        REMOTE_FILE_URL,
    )

    assert_operation_link(response)
    wait_for_operation(disk_client, response, timeout=60.0)
    assert_remote_file_uploaded(disk_client, file_path)
    download_url = disk_client.get_download_link(file_path).json()["href"]
    download = requests.get(download_url, timeout=30)
    assert download.status_code == requests.codes.ok
    assert download.content == REMOTE_FILE_CONTENT


def test_upload_from_url_fields_limits_operation_link(
    disk_client: YandexDiskClient,
    sandbox_path: str,
) -> None:
    """Positive: fields limits the Link while preserving its operation URL."""
    file_path = f"{unique_child(sandbox_path, 'remote-upload-fields')}.txt"

    response = disk_client.upload_resource_from_url(
        file_path,
        REMOTE_FILE_URL,
        fields="href,method",
    )

    assert_operation_link(
        response,
        expected_fields={"href", "method"},
    )
    wait_for_operation(disk_client, response, timeout=60.0)
    assert_remote_file_uploaded(disk_client, file_path)


def test_upload_from_url_supports_disable_redirects(
    disk_client: YandexDiskClient,
    sandbox_path: str,
) -> None:
    """Positive: disable_redirects=true accepts a direct non-redirecting URL."""
    file_path = f"{unique_child(sandbox_path, 'remote-upload-direct')}.txt"

    response = disk_client.upload_resource_from_url(
        file_path,
        REMOTE_FILE_URL,
        disable_redirects=True,
    )

    assert_operation_link(response)
    wait_for_operation(disk_client, response, timeout=60.0)
    assert_remote_file_uploaded(disk_client, file_path)


def test_upload_from_url_supports_unicode_and_spaces(
    disk_client: YandexDiskClient,
    sandbox_path: str,
) -> None:
    """Edge case: Unicode and spaces in the destination path are preserved."""
    file_path = f"{unique_child(sandbox_path, 'загрузка по ссылке')}.txt"

    response = disk_client.upload_resource_from_url(
        file_path,
        REMOTE_FILE_URL,
    )

    assert_operation_link(response)
    wait_for_operation(disk_client, response, timeout=60.0)
    metadata = assert_remote_file_uploaded(disk_client, file_path)
    assert metadata["name"] == file_path.rsplit("/", maxsplit=1)[1]


def test_upload_from_url_existing_file_creates_numbered_copy(
    disk_client: YandexDiskClient,
    sandbox_path: str,
) -> None:
    """Edge case: an occupied file path produces a numbered sibling."""
    file_path = f"{unique_child(sandbox_path, 'remote-upload-conflict')}.txt"
    imported_path = numbered_collision_path(file_path)
    before = upload_test_file(disk_client, file_path, b"keep me")

    response = disk_client.upload_resource_from_url(
        file_path,
        REMOTE_FILE_URL,
    )

    assert_operation_link(response)
    operation = wait_for_operation_result(disk_client, response, timeout=60.0)
    assert operation == {"status": "success"}
    imported = assert_remote_file_uploaded(disk_client, imported_path)
    after = disk_client.get_resource(file_path).json()
    assert after["md5"] == before["md5"]
    assert after["size"] == before["size"]
    assert imported["name"].endswith(" (1).txt")


def test_upload_from_url_directory_collision_creates_numbered_file(
    disk_client: YandexDiskClient,
    sandbox_path: str,
) -> None:
    """Edge case: an occupied directory path produces a numbered file."""
    folder_path = unique_child(sandbox_path, "remote-upload-over-dir")
    imported_path = numbered_collision_path(folder_path)
    disk_client.create_folder(folder_path)

    response = disk_client.upload_resource_from_url(
        folder_path,
        REMOTE_FILE_URL,
    )

    assert_operation_link(response)
    operation = wait_for_operation_result(disk_client, response, timeout=60.0)
    assert operation == {"status": "success"}
    imported = assert_remote_file_uploaded(disk_client, imported_path)
    assert disk_client.get_resource(folder_path).json()["type"] == "dir"
    assert imported["name"].endswith(" (1)")


def test_upload_from_url_without_required_path_returns_400(
    disk_client: YandexDiskClient,
) -> None:
    """Negative: path is a required query parameter."""
    response = disk_client.upload_resource_from_url(
        None,
        REMOTE_FILE_URL,
        expected_statuses={400},
    )

    payload = assert_error_response(response, requests.codes.bad_request)
    assert payload["error"] == "FieldValidationError"


def test_upload_from_url_without_required_url_returns_400(
    disk_client: YandexDiskClient,
    sandbox_path: str,
) -> None:
    """Negative: url is a required query parameter."""
    file_path = f"{unique_child(sandbox_path, 'remote-upload-no-url')}.txt"

    response = disk_client.upload_resource_from_url(
        file_path,
        None,
        expected_statuses={400},
    )

    payload = assert_error_response(response, requests.codes.bad_request)
    assert payload["error"] == "FieldValidationError"


def test_upload_from_url_rejects_invalid_url(
    disk_client: YandexDiskClient,
    sandbox_path: str,
) -> None:
    """Negative: url must be an absolute supported external URL."""
    file_path = f"{unique_child(sandbox_path, 'remote-upload-invalid-url')}.txt"

    response = disk_client.upload_resource_from_url(
        file_path,
        "not-an-absolute-url",
        expected_statuses={400},
    )

    assert_error_response(response, requests.codes.bad_request)


def test_upload_from_url_to_missing_parent_is_rejected(
    disk_client: YandexDiskClient,
    sandbox_path: str,
) -> None:
    """Negative: the destination's direct parent must exist."""
    missing_parent = unique_child(sandbox_path, "remote-missing-parent")
    file_path = f"{missing_parent}/result.txt"

    response = disk_client.upload_resource_from_url(
        file_path,
        REMOTE_FILE_URL,
        expected_statuses={409},
    )

    payload = assert_error_response(response, requests.codes.conflict)
    assert payload["error"] == "DiskPathDoesntExistsError"


def test_upload_from_url_with_invalid_token_returns_401(
    unauthorized_disk_client: YandexDiskClient,
    sandbox_path: str,
) -> None:
    """Negative: invalid OAuth credentials cannot start an import."""
    file_path = f"{unique_child(sandbox_path, 'unauthorized-remote-upload')}.txt"

    response = unauthorized_disk_client.upload_resource_from_url(
        file_path,
        REMOTE_FILE_URL,
        expected_statuses={401},
    )

    payload = assert_error_response(response, requests.codes.unauthorized)
    assert payload["error"] == "UnauthorizedError"
